name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: install-dependencies
      - name: Build Production
        run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: install-dependencies
      - name: Lint Check
        run: yarn lint:check
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: install-dependencies
      - name: Format Check
        run: yarn format:check
  deploy:
    runs-on: ubuntu-latest
    needs: [build, lint, format]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: install-dependencies
      - name: Deploy to Production
        run: echo "Deploying to production..."
